### ISSUE TITLE
ProjectTo and EnumConversion when enum is stored as string doesn't work

### ISSUE THREAD

**Issue by frankhaugen** [AutoMapper/AutoMapper.Extensions.EnumMapping#10]
### Source/destination types

```csharp
//Source 
    public class Integration
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Status Status { get; set; }
   }

   public enum Status
    {
        Active,
        InActive,
        Deleted
    }

// Destination 
    public class IntegrationHeaderResponse
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Status Status { get; set; }
    }

    public enum Status // Different namespace
    {
        Active,
        InActive,
        Deleted
    }
```

### Mapping configuration

```csharp
    public class EnumProfile : Profile
    {
        public EnumProfile()
        {
            CreateMap<Status, Client.Models.Enums.Status>().ConvertUsingEnumMapping(expression => expression.MapByName(true));
        }
    }
```

### Expected behavior

Projection to work, (I am using Enum/String Conversion in entity framework core (.net 5) entity config

### Actual behavior

```
Test Name:	Company.IntegrationEngine.Tests.Controllers.IntegrationsControllerTests.GetDevEx_StateUnderTest_ExpectedBehavior
Test FullName:	Company.IntegrationEngine.Tests.Company.IntegrationEngine.Tests.Controllers.IntegrationsControllerTests.Company.IntegrationEngine.Tests.Controllers.IntegrationsControllerTests.GetDevEx_StateUnderTest_ExpectedBehavior
Test Source:	C:\repos\Company.IntegrationEngine\Company.IntegrationEngine.Tests\Controllers\IntegrationsControllerTests.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	Company.IntegrationEngine.Tests.Controllers.IntegrationsControllerTests.GetDevEx_StateUnderTest_ExpectedBehavior
Test Outcome:	Failed
Result StackTrace:	
at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.ConstantVerifyingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VerifyNoClientConstant(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at DevExtreme.AspNet.Data.Async.ReflectionAsyncAdapter.InvokeToListAsync[T](MethodInfo method, IQueryProvider provider, Expression expr, CancellationToken cancellationToken)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ExecExprAsync[R](Expression expr)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.LoadAsync()
   at Company.IntegrationEngine.Api.Controllers.IntegrationsController.GetDevEx(Guid organizationId, DataSourceLoadOptions loadOptions) in C:\repos\Company.IntegrationEngine\Company.IntegrationEngine.Api\Controllers\IntegrationsController.cs:line 63
   at Company.IntegrationEngine.Tests.Controllers.IntegrationsControllerTests.GetDevEx_StateUnderTest_ExpectedBehavior() in C:\repos\Company.IntegrationEngine\Company.IntegrationEngine.Tests\Controllers\IntegrationsControllerTests.cs:line 89
--- End of stack trace from previous location ---
Result Message:	System.InvalidOperationException : The client projection contains a reference to a constant expression of 'AutoMapper.Extensions.EnumMapping.Internal.CustomMapExpressionFactory<Company.IntegrationEngine.Data.Entities.Enums.Status, Company.IntegrationEngine.Client.Models.Enums.Status>' through the instance method 'ConvertEnumValue'. This could potentially cause a memory leak; consider making the method static so that it does not capture constant in the instance. See https://go.microsoft.com/fwlink/?linkid=2103067 for more information.


```

### Steps to reproduce

```csharp
        [HttpGet("dx")]
        [ProducesResponseType(typeof(CustomQueryResponse), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetDevEx([FromRoute] Guid organizationId, DataSourceLoadOptions loadOptions)
        {
            var queryableIntegrations = _integrationService.GetIntegrationIQueryable(organizationId);
            var queryableIntegrationHeaders = _mapper.ProjectTo<IntegrationHeaderResponse>(queryableIntegrations);
            var result = await DataSourceLoader.LoadAsync(queryableIntegrationHeaders, loadOptions);

            return Ok(new CustomQueryResponse
            {
                Data = result.data,
                GroupCount = result.groupCount,
                Summary = result.summary,
                TotalCount = result.totalCount
            });
        }
```

**Comment by HenkKin** [comment]
ProjectTo in combination with EnumMapping is not working at the moment. Alternative is to map using default AutoMapper convention or using:

`CreateMap<Status, Client.Models.Enums.Status>()
        .ForMember(dst => dst.Status, opt=>opt.MapFrom(src=> (int)src.Status);`

**Comment by lbargaoanu** [comment]
Mapping enums by value is [built in](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/EnumProjectionMapper.cs) with `ProjectTo`, no map needed.

**Comment by GrayPockets** [comment]
Where you ever able to find a work-around @frankhaugen ?

I ran into the same problem. Mapping enums by value doesn't work when using EntityFramework enum is stored as string. Specifically using EnumToStringConverter: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.enumtostringconverter-1?view=efcore-5.0
`builder`
`    .Property(thisEntity => thisEntity.ThisEnum)`
`    .HasConversion(new EnumToStringConverter<MyEnum>())`
`    .HasMaxLength(13);`

Using ConvertUsingEnumMapping or trying to use Enum.Parse gave me the same error as you.

When using the default automapper convention or the above example by @HenkKin You get a different error:
`invalid input syntax for integer: "MyEnumString"`

**Comment by lbargaoanu** [comment]
See the point [here](https://github.com/AutoMapper/AutoMapper/discussions/3763).

**Comment by GrayPockets** [comment]
I gave up and converted all my enums to integers. Makes database queries harder to read.
